### ISSUE TITLE
Debloat HarmonicBalance.jl

### ISSUE THREAD

**Issue by oameye** [NonlinearOscillations/HarmonicBalance.jl#98]
## Problem
The current implementation of HarmonicBalance.jl package is becoming bloated and difficult to maintain regarding building out the future NonlinearOscillations ecosystem. It would be beneficial to split it into multiple smaller packages in order to improve maintainability and ease of use. In that way, the packages under the ecosystem becomes more more lightweight, focused on a specific set of functionality.

## Proposed solution
Mimic the [SCIML ecosystem](https://docs.sciml.ai/Overview/stable/overview/#overview) by creating a hierarchical structure of packages. Create a main interface package at the top of the hierarchy that serves as a low-dependency common interface for libraries downstream. Split the current package into smaller, focused packages that are designed to work well together. Another, maybe more relevant, ecosystem who does a similar thing would be [QuantumOptics.jl](https://github.com/qojulia).

## Implementation plan
* [ ] Create a new main interface package and move the common interface code into it. This would be the package now called [HarmonicBalanceBase.jl](https://github.com/NonlinearOscillations/HarmonicBalanceBase.jl).
* [ ] Identify the main functionalities of the current package that can be separated into smaller packages.
   * Computing slow-flow equations.
   * Solving slow-flow equations with Homotopy Continuation.
   * Time evolve and analyze slow-flow equations and the nonlinear oscillatory ODE's.
* [ ]  Create new packages for each of the functionalities identified in the previous step and move the corresponding code into them.
* [ ] Find good names for all extra packages.
* [ ] Test the new packages to ensure they work well together and with the main interface package.

## Additional information
* [Here](https://docs.sciml.ai/DiffEqDevDocs/stable/contributing/adding_packages/#Adding-a-new-package-to-the-common-interface) one can find some tips and tricks for making common interfaces between packages
* Package [Reexport](https://github.com/simonster/Reexport.jl) is commonly used.

**Comment by oameye** [comment]
https://docs.julialang.org/en/v1.9.0-rc2/manual/code-loading/#man-extensions
![image](https://user-images.githubusercontent.com/57623933/232705255-b5d40e83-f31a-40d8-965e-bdaeaa13e76a.png)

**Comment by oameye** [comment]
Package Extensions cannot be used as you can only extent a extisting function and cannot export new ones
